=== Nitrax198/Programaci-n/HTML5Examen2eva/public_html/xml/2-3.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="CuerpoDeElite">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="RecuersosMilitares">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="RecursoHumano" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>  
                                        <xs:element name="nombre" type="xs:string"/> 
                                        <xs:element name="PotenciaDeMuerte" type="xs:integer"/>       
                                        <xs:element name="Stress" type="xs:integer"/>       
                                        <xs:element name="MuertesACuchillo" type="xs:integer"/>       
                                        <xs:element name="NivelManejoMaquinas" type="xs:integer"/>       
                                        <xs:element name="Experiencia" type="xs:integer"/>       
                                        <xs:element name="Misiones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Mision" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="MisionReconocimiento" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>  
                                                                            <xs:element name="Fecha" type="xs:date"/> 
                                                                            <xs:element name="Lugar" type="xs:string"/>       
                                                                            <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>       
                                                                            <xs:element name="Cumplida" type="xs:boolean"/>       
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="MisionCombate" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>  
                                                                            <xs:element name="Fecha" type="xs:date"/> 
                                                                            <xs:element name="Lugar" type="xs:string"/>       
                                                                            <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>
                                                                            <xs:element name="NivelMinimoPotenciaDeMuerte" type="xs:integer"/>       
                                                                            <xs:element name="Cumplida" type="xs:boolean"/>       
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="RecursoMaterial" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>  
                                        <xs:element name="nombre" type="xs:string"/> 
                                        <xs:element name="PotenciaDeMuerte" type="xs:integer"/>
                                        <xs:element name="NivelHabilidadMinimo" type="xs:integer"/>       
                                        <xs:element name="RangoDeAcción" type="xs:integer"/>
                                        <xs:element name="Misiones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Mision" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="MisionReconocimiento" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>  
                                                                            <xs:element name="Fecha" type="xs:date"/> 
                                                                            <xs:element name="Lugar" type="xs:string"/>       
                                                                            <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>       
                                                                            <xs:element name="Cumplida" type="xs:boolean"/>       
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="MisionCombate" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>  
                                                                            <xs:element name="Fecha" type="xs:date"/> 
                                                                            <xs:element name="Lugar" type="xs:string"/>       
                                                                            <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>
                                                                            <xs:element name="NivelMinimoPotenciaDeMuerte" type="xs:integer"/>       
                                                                            <xs:element name="Cumplida" type="xs:boolean"/>       
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>              
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="RecursoVehiculo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>  
                                        <xs:element name="nombre" type="xs:string"/> 
                                        <xs:element name="PotenciaDeMuerte" type="xs:integer"/>       
                                        <xs:element name="NivelHabilidadMinimo" type="xs:integer"/>       
                                        <xs:element name="RangoDeAcción" type="xs:integer"/>       
                                        <xs:element name="Capacidad" type="xs:integer"/>
                                        <xs:element name="Misiones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="MisionReconocimiento" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>  
                                                                <xs:element name="Fecha" type="xs:date"/> 
                                                                <xs:element name="Lugar" type="xs:string"/>       
                                                                <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>       
                                                                <xs:element name="Cumplida" type="xs:boolean"/>       
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="MisionCombate" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>  
                                                                <xs:element name="Fecha" type="xs:date"/> 
                                                                <xs:element name="Lugar" type="xs:string"/>       
                                                                <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>
                                                                <xs:element name="NivelMinimoPotenciaDeMuerte" type="xs:integer"/>       
                                                                <xs:element name="Cumplida" type="xs:boolean"/>       
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>       
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Misiones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MisionReconocimiento" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>  
                                        <xs:element name="Fecha" type="xs:date"/> 
                                        <xs:element name="Lugar" type="xs:string"/>       
                                        <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>       
                                        <xs:element name="Cumplida" type="xs:boolean"/>       
                                        <xs:element name="Recursos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Recurso" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Uso" type="xs:string"/>
                                                                <xs:element name="Recursos">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Recurso" minOccurs="0" maxOccurs="unbounded">
                                                                                <xs:complexType> 
                                                                                    <xs:sequence>
                                                                                        <xs:element name="nombre" type="xs:string"/> 
                                                                                        <xs:element name="PotenciaDeMuerte" type="xs:integer"/>       
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="MisionCombate" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>  
                                        <xs:element name="Fecha" type="xs:date"/> 
                                        <xs:element name="Lugar" type="xs:string"/>       
                                        <xs:element name="NivelDeExperienciaGanada" type="xs:integer"/>       
                                        <xs:element name="NivelMinimoPotenciaDeMuerte" type="xs:integer"/>       
                                        <xs:element name="Cumplida" type="xs:boolean"/>       
                                        <xs:element name="Recursos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Recurso" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Uso" type="xs:string"/>
                                                                <xs:element name="Recursos">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Recurso" minOccurs="0" maxOccurs="unbounded">
                                                                                <xs:complexType> 
                                                                                    <xs:sequence>
                                                                                        <xs:element name="nombre" type="xs:string"/> 
                                                                                        <xs:element name="PotenciaDeMuerte" type="xs:integer"/>       
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nitrax198/Programaci-n/HTML5Examen2eva/public_html/xml/2-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<CuerpoDeElite
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/Programaci-n/Formularios/public_html/Xml/2-3.xsd'>
    <RecuersosMilitares>
        <RecursoHumano>
            <nombre>dddd</nombre>
            <PotenciaDeMuerte>1111</PotenciaDeMuerte>
            <Stress>1111</Stress>
            <MuertesACuchillo>1111</MuertesACuchillo>
            <NivelManejoMaquinas>2222</NivelManejoMaquinas>
            <Experiencia>333</Experiencia>
            <Misiones>
                <Mision>
                    <MisionReconocimiento>
                        <Fecha>12/3/2018</Fecha>
                        <Lugar>españa</Lugar>
                        <NivelDeExperienciaGanada>222</NivelDeExperienciaGanada>
                        <Cumplida>true</Cumplida>
                    </MisionReconocimiento>
                    <MisionCombate>
                        <Fecha>12/3/1028</Fecha>
                        <Lugar>fff</Lugar>
                        <NivelDeExperienciaGanada>3</NivelDeExperienciaGanada>
                        <NivelMinimoPotenciaDeMuerte>4</NivelMinimoPotenciaDeMuerte>
                        <Cumplida>5</Cumplida>
                    </MisionCombate>
                </Mision>
            </Misiones>
        </RecursoHumano>
        <RecursoMaterial>
            <nombre>ffff</nombre>
            <PotenciaDeMuerte>2222</PotenciaDeMuerte>
            <NivelHabilidadMinimo>44444</NivelHabilidadMinimo>
            <RangoDeAcción>5555</RangoDeAcción>
            <Misiones>
            </Misiones>
        </RecursoMaterial>
        <RecursoVehiculo>
            <nombre>7777</nombre>
            <PotenciaDeMuerte>3333</PotenciaDeMuerte>
            <NivelHabilidadMinimo>1222</NivelHabilidadMinimo>
            <RangoDeAcción>333</RangoDeAcción>
            <Capacidad>4444</Capacidad>
            <Misiones>
            </Misiones>
        </RecursoVehiculo>
    </RecuersosMilitares>
    <Misiones>
    </Misiones>

</CuerpoDeElite>
