=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Biblioteca.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libros" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro"  maxOccurs="unbounded" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="isbn" type="xs:String"/>
                                        <xs:element name="titulo" type="xs:String"/>
                                        <xs:element name="autor"  type="xs:String"/>
                                        <xs:element name="numeroPgs"  type="xs:integer"/>
                                        <xs:element name="prestado"  type="xs:Boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Usuarios" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Usuario" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Usuario"  maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nombre" type="xs:String"/>
                                                    <xs:element name="ArrayLibros"  maxOccurs="3">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="isbn" type="xs:String"/>
                                                                <xs:element name="titulo" type="xs:String"/>
                                                                <xs:element name="autor"  type="xs:String"/>
                                                                <xs:element name="numeroPgs"  type="xs:integer"/>
                                                                <xs:element name="prestado"  type="xs:Boolean"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Biblioteca
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/Programaci-n/HTMLXML/public_html/XML/Biblioteca.xsd'>
    <libros>
        <libro>
            <isbn>isbnsgt6</isbn>
            <titulo>El jardín de las palabras</titulo>
            <autor>Carlos</autor>
            <numeroPgs>325</numeroPgs>
            <prestado>true</prestado>
        </libro>
    </libros>
    <Usuarios>
        <Usuario>
            <Usuario>
                <Nombre> Juanma </Nombre>
                <ArrayLibros>
                    <isbn>isbnsgt6</isbn>
                    <titulo>El jardín de las palabras</titulo>
                    <autor>Carlos</autor>
                    <numeroPgs>325</numeroPgs>
                    <prestado>true</prestado>
                </ArrayLibros>
            </Usuario>
        </Usuario>
    </Usuarios>

</Biblioteca>
