=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Merkadona.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="Merkadona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Empleado">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ID" type="xs:integer"/>
                                        <xs:element name="Nombre" type="xs:String"/>
                                        <xs:element name="Reponedora"  maxOccurs="unbounded" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="TotalNumProds"  type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Cajera"  maxOccurs="unbounded" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="PrecioTotal"  type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CantidadEnStock" type="xs:integer"/>
                            <xs:element name="PrecioBase" type="xs:integer"/>
                            <xs:element name="Nombre" type="xs:String"/>
                            <xs:element name="Perecederos"  maxOccurs="unbounded" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FechaCaducidad"  type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Merkadona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
\and open the template in the editor.
-->


<Merkadona
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Merkadona.xsd'>
    <Empleados>
        <Empleado>
            <ID>2834</ID>
            <Nombre>Maria</Nombre>
            <Reponedora>
                <TotalNumProds>150</TotalNumProds>
            </Reponedora>
            <Cajera>
                <PrecioTotal>20</PrecioTotal>
            </Cajera>
        </Empleado>
    </Empleados>
    <Productos>
        <CantidadEnStock>150</CantidadEnStock>
        <PrecioBase>30</PrecioBase>
        <Nombre>Platano</Nombre>
        <Perecederos>
            <FechaCaducidad>1908/12/12</FechaCaducidad>
        </Perecederos>
    </Productos>

</Merkadona>
