=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Polideportivo.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Polideportivo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Alumno"  maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:String"/>
                            <xs:element name="Apellido" type="xs:String"/>
                            <xs:element name="PagaAlMes" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Horario"  maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Dias" type="xs:String"/>
                            <xs:element name="HoraFinal" type="xs:integer"/>
                            <xs:element name="HoraInicial" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Actividad"  maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo" type="xs:String"/>
                            <xs:element name="Plazas" type="xs:String"/>
                            <xs:element name="PlazasLibres" type="xs:String"/>
                            <xs:element name="Precio" type="xs:String"/>
                            <xs:element name="Horario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Dias" type="xs:String"/>
                                        <xs:element name="HoraFinal" type="xs:integer"/>
                                        <xs:element name="HoraInicial" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ArrayAlumnos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:String"/>
                                        <xs:element name="Apellido" type="xs:String"/>
                                        <xs:element name="PagaAlMes" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/Polideportivo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Polideportivo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Polideportivo.xsd'>
    <Alumno>
        <Nombre>Julio</Nombre>
        <Apellido>Hernandez</Apellido>
        <PagaAlMes>120</PagaAlMes>
    </Alumno>
    <Horario>
        <Dias>Lunes</Dias>
        <HoraFinal>10</HoraFinal>
        <HoraInicial>12</HoraInicial>
    </Horario>
    <Actividad>
        <tipo>Boxeo</tipo>
        <Plazas>13</Plazas>
        <PlazasLibres>10</PlazasLibres>
        <Precio>120</Precio>
        <Horario>
            <Dias>10</Dias>
            <HoraFinal>10</HoraFinal>
            <HoraInicial>12</HoraInicial>
        </Horario>
        <ArrayAlumnos>
            <Nombre>haime</Nombre>
            <Apellido>Gimenez</Apellido>
            <PagaAlMes>120</PagaAlMes>
        </ArrayAlumnos>
    </Actividad>

</Polideportivo>
