=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/ZanalKar.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/ZanalKar.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Vehiculos SYSTEM "ZanalKar.dtd">

    <Vehiculos>
    ...
    </Vehiculos>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Vehiculos (VehiculosAMotor|Bicis)*>
<!ATTLIST Vehiculos
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VehiculosAMotor (Motos|Coches|Quads)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Motos (Color|Marca|PreciCompra|PreciVenta|Matricula|KMUso)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Color (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Marca (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PreciCompra (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PreciVenta (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Matricula (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT KMUso (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Coches (Color|Marca|PreciCompra|PreciVenta|Matricula|KMUso)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Quads (Color|Marca|PreciCompra|PreciVenta|Matricula|KMUso)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Bicis (Color|Marca|PreciCompra|PreciVenta|NumeroDeMarcas|TamañoRuedas|TipoDeCambio)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NumeroDeMarcas (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TamañoRuedas (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TipoDeCambio (#PCDATA)>

=== Nitrax198/Programaci-n/HTMLXML/public_html/XML/ZanalKar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE Zanalcar SYSTEM "ZanalKar.dtd">

<Vehiculos
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ZanalKar.xsd'>
    <VehiculosAMotor>
        <Motos>
            <Color>Rosa</Color>
            <Marca>harleyDavidson</Marca>
            <PreciCompra>25000</PreciCompra>
            <PreciVenta>30000</PreciVenta>
            <Matricula>404HTML</Matricula>
            <KMUso>10</KMUso>
        </Motos>
        <Coches>
            <Color>Marron</Color>
            <Marca>CielCadilac</Marca>
            <PreciCompra>500000</PreciCompra>
            <PreciVenta>600000</PreciVenta>
            <Matricula>404Error</Matricula>
            <KMUso>20</KMUso>
        </Coches>
        <Quads>
            <Color>Verde</Color>
            <Marca>Epona</Marca>
            <PreciCompra>100</PreciCompra>
            <PreciVenta>150</PreciVenta>
            <Matricula>Hyrule</Matricula>
            <KMUso>30</KMUso>
        </Quads>
    </VehiculosAMotor>
    <Bicis>
        <Color>Negro</Color>
        <Marca>Rocinante</Marca>
        <PreciCompra>3</PreciCompra>
        <PreciVenta>2</PreciVenta>
        <NumeroDeMarcas>3</NumeroDeMarcas>
        <TamañoRuedas>1</TamañoRuedas>
        <TipoDeCambio>Ninguno</TipoDeCambio>
    </Bicis>

</Vehiculos>
